from cli_detroix23.base import style as style

class Code:
    string: str
    codes: list[int]
    
    def __init__(self, string: str = '', codes: list[int] = ...) -> None: ...
    def fuse(self, other: Code) -> Code: ...
    def __add__(self, other: object) -> str | Code: ...

def code_clean(string: str) -> int: ...
def code_clean_all(string: str) -> list[int]: ...
def code_fuse(codes: list[int]) -> str: ...
