from cli_detroix23.base import specials as specials
from cli_detroix23.maths import maths as maths

def up(times: int = 1, flush: bool = False) -> None: ...
def right(times: int = 1, flush: bool = False) -> None: ...
def down(times: int = 1, flush: bool = False) -> None: ...
def left(times: int = 1, flush: bool = False) -> None: ...
def home(flush: bool = False) -> None: ...
def fin(flush: bool = False) -> None: ...
def next_line(times: int = 1, flush: bool = False) -> None: ...
def previous_line(times: int = 1, flush: bool = False) -> None: ...
def goto_column(x: int, flush: bool = False) -> None: ...
def goto(position: maths.Size, flush: bool = False) -> None: ...
def clear_line(times: int = 1, flush: bool = False) -> None: ...
def clear_to_bottom(flush: bool = False) -> None: ...
def scroll(lines: int, flush: bool = False) -> None: ...
def cursor_save_position(flush: bool = False) -> None: ...
def cursor_restore_position(flush: bool = False) -> None: ...
def cursor_show(flush: bool = False) -> None: ...
def cursor_hide(flush: bool = False) -> None: ...
