from cli_detroix23.base import style as style

def select_gh_style(message: str, start: str = '$', usage: str = '[↑ ↓ - Enter to accept]') -> str: ...
def input_gh_style(message: str, start: str = '#', usage: str = '', default: str = '') -> str: ...
def bool_gh_style(message: str, start: str = '?', usage: str = 'y/ n', default: str = 'y') -> str: ...
