from cli_detroix23.compatibility import types as types
from typing import Final

FILE_ID: Final[int]
SETTINGS: Final[types.Attr]
KEYS: Final[list[str]]
CC: Final[list[str]]

def get_settings(file_id: int) -> types.Attr: ...
def settings_difference(s1: types.Attr, s2: types.Attr) -> dict[str, tuple[int, int]]: ...
def set_to_default() -> None: ...
def print_attr(settings: types.Attr) -> None: ...
def test_present_settings() -> None: ...
def main() -> None: ...
