from cli_detroix23.base import controls as controls, specials as specials
from cli_detroix23.inputs import fetch as fetch, keys as keys

class SysReading:
    running: bool
    def __init__(self) -> None: ...
    def run(self) -> None: ...

def run_sys_reading() -> None: ...
def run_basic_keys() -> None: ...
