from cli_detroix23.compatibility import debug as debug, platform as platform
from cli_detroix23.inputs import keys as keys

def get(*, allow_keyboard_interrupt: bool = True) -> keys.Key: ...
def compare(key_a: str | keys.Key, key_b: str | keys.Key) -> bool: ...
def fetch_target(info: keys.Info) -> None: ...
def fetch(info: keys.Info) -> None: ...
