
from cli_detroix23.compatibility import types as types

class Size:
    x: int
    y: int

    def __init__(self, x: int = 0, y: int = 0) -> None: ...
    def area(self) -> int: ...
    def __hash__(self) -> int: ...
    @staticmethod
    def terminal_size() -> Size: ...

class Vector2D:
    x: float
    y: float
    
    def __init__(self, x: float = 0, y: float = 0) -> None: ...
    def magnitude(self) -> float: ...
    def normalize(self) -> None: ...
    def __eq__(self, target: object) -> bool: ...
    def __hash__(self) -> int: ...
    def clone(self) -> Vector2D: ...

def both_range(number: int) -> list[int]: ...
def middle_range(number: int) -> list[int]: ...
def create_table(size: Size, character: str = '') -> types.Table2D: ...
def create_table_like(model: types.Table2D, character: str = '') -> types.Table2D: ...
