from cli_detroix23.compatibility import types as types
from cli_detroix23.maths import maths as maths

RELATIVE_NEIGHBOURS: set[maths.Vector2D]

def simple_cos(a: int) -> int: ...
def simple_sin(a: int) -> int: ...
def rotation(table: types.Table2D, angle: int) -> types.Table2D: ...
def transpose(table: types.Table2D) -> types.Table2D: ...
def mirror(table: types.Table2D) -> types.Table2D: ...
def simple_rotation(table: types.Table2D, angle: int) -> types.Table2D: ...
