from cli_detroix23.animations import screen as screen
from cli_detroix23.base import style as style
from cli_detroix23.maths import maths as maths, transformations as transformations

from enum import Enum
from typing import Sequence

class Droplet:
    char: str
    position: maths.Vector2D
    last_chars: list[str]
    frames_to_move: int
    screen: Matrix

    def __init__(self, screen: Matrix) -> None: ...
    def update(self) -> None: ...
    def full_tail(self) -> list[str]: ...

class Matrix(screen.Screen):
    digital_rain: list[Droplet]
    character_random_range: tuple[int, int]
    infos: bool
    start_time: float
    
    def __init__(self, frame_delay: float, character_random_range: tuple[int, int] = (40, 127), infos: bool = False, activate_threads: bool = False) -> None: ...
    def time_elapsed(self) -> float: ...
    def updater(self) -> None: ...
    def drawer(self) -> None: ...

class CellState(Enum):
    DEAD = 0
    ALIVE = 1
    VOID = 2

class GameOfLife(screen.Screen):
    board: list[list[CellState]]

    def __init__(self, void_char: str = '.', frame_delay: float = 0.1, global_style: str = '', debug: bool = False, deactivate_screen: bool = False, activate_threads: bool = False) -> None: ...
    def updater(self) -> None: ...
    def drawer(self) -> None: ...
    def set_cell(self, coordinates: maths.Size, state: CellState) -> CellState: ...
    def set_multiple(self, coordinates: Sequence[maths.Size], state: CellState) -> None: ...
    def count_neighbours(self, coordinates: maths.Vector2D) -> int: ...

def run_matrix() -> None: ...
def run_game_of_life() -> None: ...
def main() -> None: ...
