import threading
from cli_detroix23.base import controls as controls, style as style
from cli_detroix23.compatibility import debug as debug, defaults as defaults
from cli_detroix23.inputs import fetch as fetch, keys as keys
from cli_detroix23.maths import maths as maths
from enum import Enum
from typing import Callable

class ReadingWay(Enum):
    LEFT_RIGHT = 0
    RIGHT_LEFT = 1
    UP_DOWN = 2
    DOWN_UP = 3

class Screen:
    running: bool
    size: maths.Size
    debug: bool
    deactivate_screen: bool
    void_char: str
    frame_delay: float
    global_style: str
    char_table: list[list[str]]
    previous_char_table: list[list[str]]
    read_keys: bool
    activate_threads: bool
    threads: dict[str, threading.Thread]
    def __init__(self, void_char: str = '.', frame_delay: float = 0.1, global_style: str = '', debug: bool = False, deactivate_screen: bool = False, read_keys: bool = False, activate_threads: bool = False) -> None: ...
    def start_threads(self) -> int: ...
    def join_threads(self) -> int: ...
    def run(self, updater: Callable[[], None], drawer: Callable[[], None]) -> None: ...
    def update_size(self) -> tuple[int, int]: ...
    @property
    def frames(self) -> int: ...
    @property
    def pressed_key(self) -> keys.Key | None: ...
    def frames_reset(self) -> None: ...
    def blank_char_table(self) -> list[list[str]]: ...
    def clear_char(self, position: maths.Vector2D) -> None: ...
    def write(self, message: str | list[str], start: maths.Vector2D, way: ReadingWay = ..., styles: str = '') -> int: ...
    def write_table(self, table: list[list[str]], position: maths.Vector2D, way: ReadingWay = ..., styles: str = '') -> None: ...
    def print_char_table(self) -> None: ...
    def total_char_table_len(self) -> int: ...
